export const APP_ROUTES = {
  root: '',
  login: 'auth/login',
  recoverPassword: 'auth/recover-password',
  newPassword: 'auth/new-password',
  twoFactor: 'auth/two-factor',
  main: 'main',
  home: 'main/home',
  helpdesk: 'main/helpdesk',
  profile: 'main/profile' ,
  mail: 'main/correo',
  systemarea: 'main/modulo/sistema/configuracion',
  area: 'main/modulo',
  module: 'main/modulo',
} as const;
